### PR TITLE
protobuf proxy

### PR DESCRIPTION
**Pull request by limpbrains**
`GetInfo` and `GetTransactions` lnd rpc calls works through one proxy `sendCommand` method

copy-paste from  blixt-wallet

### CODE REVIEW

**Comment by Overtorment** [comment]
can you add android counterpart as well? preferably kotlin, I want to play around with it on emulator.

my main concern at the moment is that `proto/index.js` > 2Mb, is there a way to measure the performance impact of this..?
otherwise looks pretty sleek.

**Comment by Overtorment** [comment]
@marcosrdz what are your thoughts on this?

**Comment by Overtorment** [comment]
also, some lndmobile methods work with plain callbacks, and some with streams - can you provide examples of that as well?

**Comment by limpbrains** [comment]
Thanks for the thoughts. Will work on android and streaming api.
In terms of the size, I think we can load these definitions dynamically if needed, I think RN should support it, since babel does

**Comment by Overtorment** [comment]
some more thoughts:

pure native implementation I started has its merit: its super fast because its native; error-prone because everything is checked during compile-time; you have to code it only once - lnd's rpc wont change in principle, when they need to change stuff they add new methods (like SendPaymentV2) to maintain backward compatibility, so you just code and forget; and you don't need additional packages like npm's protobufjs.
the drawback is ofcourse you have to implement things twice: swift AND kotlin, but tbh once you implemented one method, implementing the rest is just copy-paste brain-dead work. 

as for huge size of `proto/index.js` - maybe its possible to manually edit it and throw away large parts that are not needed

**Comment by marcosrdz** [comment]
Personally I prefer native calls even though they are more work. They are better in the long term since we would inherit native performance and optimizations done by Apple and Google.

**Comment by limpbrains** [comment]
**Performance**

I believe protobuf can even be faster.

As I understand, all communications between JS and RN environments are JSON-encoded.
https://reactnative.dev/docs/native-modules-ios#synchronous-methods
So if your Native code returns some complex object, it will be json-encoded.
In case of sending a protobuf message, Native code returns String and JS get a String. There is no JSON encode-decode

Yes we are shifting protobuf encode-decode to JS, but Protobuf.js is faster than JSON 
https://github.com/protobufjs/protobuf.js#performance

Request-response with Native approach:
JS -> json.encode -> RN -> json.decode -> protobuf.encode -> LND -> RN -> protobuf.decode -> json.encode -> JS -> json.decode

Request-response with Protobuf approach:
JS -> protobuf.encode -> json.encode -> RN -> json.decode -> LND -> RN -> JS -> protobuf.decode 

**Simplicity**

>  the drawback is ofcourse you have to implement things twice: swift AND kotlin, but tbh once you implemented one method, implementing the rest is just copy-paste brain-dead work.

`SendPaymentV2` has 20 arguments. Some of them are optional, some are not. It will be a huge pain to map all rpc calls correctly. 

protobuf is strictly-typed protocol, you can't shoot yourself in the foot with it

**JS Performance**
This is a real problem. Especially for old android phones. protobuf.js is big and compiled proto files are too 

PS
It would be nice if we can auto-generate Native code for proto files :)
I understand that JS is a single-thread and doing there less is probably better.
WIll try to do a simple speed test

**Comment by Overtorment** [comment]
Good thing is that we can settle on some approach, or even mixed approach,
and deliver something to production. And then change how it works under the
hood

**Comment by limpbrains** [comment]
stream example
```
const subscription = await RnLnd.subscribeTransactions((x) => console.info('SubscribeTransactions event', x));
```

**Pull request closed without merging**
